# forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import Optional

class SClienteForm(FlaskForm):
    nro_cli = StringField('Número Cliente', validators=[Optional()])
    num_soc = StringField('Número Socio', validators=[Optional()])
    act_ivo = StringField('Activo', validators=[Optional()])
    ape_cli = StringField('Apellido', validators=[Optional()])
    nom_cli = StringField('Nombre', validators=[Optional()])
    nombrer = StringField('Nombre Razon', validators=[Optional()])
    dom_cli = StringField('Domicilio', validators=[Optional()])
    loc_cli = StringField('Localidad', validators=[Optional()])
    postal = StringField('Código Postal', validators=[Optional()])
    pro_cli = StringField('Provincia', validators=[Optional()])
    con_doc = StringField('Condición Documento', validators=[Optional()])
    doc_cli = StringField('Documento', validators=[Optional()])
    nac_nal = StringField('Nacionalidad', validators=[Optional()])
    tip_cui = StringField('Tipo Cuit', validators=[Optional()])
    cuit = StringField('CUIT', validators=[Optional()])
    con_iva = StringField('Condición IVA', validators=[Optional()])
    nac_cli = StringField('Nacimiento', validators=[Optional()])
    est_civ = StringField('Estado Civil', validators=[Optional()])
    ocu_cli = StringField('Ocupación', validators=[Optional()])
    act_cli = StringField('Actividad', validators=[Optional()])
    tel_fax = StringField('Tel/Fax', validators=[Optional()])
    cia_ase = StringField('Compañía Aseguradora', validators=[Optional()])
    cip_cli = StringField('CIP CLI', validators=[Optional()])
    cip_cl2 = StringField('CIP CL2', validators=[Optional()])
    cip_cl3 = StringField('CIP CL3', validators=[Optional()])
    cip_end = StringField('CIP Endoso', validators=[Optional()])
    cip_res = StringField('CIP Rescate', validators=[Optional()])
    pol_iza = StringField('Póliza', validators=[Optional()])
    pol_iz2 = StringField('Póliza 2', validators=[Optional()])
    des_de = StringField('Desde', validators=[Optional()])
    has_ta = StringField('Hasta', validators=[Optional()])
    cob_ert = StringField('Cobertura', validators=[Optional()])
    for_pag = StringField('Forma Pago', validators=[Optional()])
    pat_ent = StringField('Patente', validators=[Optional()])
    cha_sis = StringField('Chasis', validators=[Optional()])
    ano_mod = StringField('Año Modelo', validators=[Optional()])
    mot_or = StringField('Motor', validators=[Optional()])
    val_or = StringField('Valor', validators=[Optional()])
    uso_vei = StringField('Uso Vehículo', validators=[Optional()])
    res_civ = StringField('Responsabilidad Civil', validators=[Optional()])
    ant_cip = StringField('Ant. CIP', validators=[Optional()])
    nro_rec = StringField('Número Recibo', validators=[Optional()])
    can_cuo = StringField('Cantidad Cuotas', validators=[Optional()])
    imp_cuo = StringField('Importe Cuota', validators=[Optional()])
    tot_pol = StringField('Total Póliza', validators=[Optional()])
    pre_mio = StringField('Premio', validators=[Optional()])
    recargos = StringField('Recargos', validators=[Optional()])
    deremi = StringField('Derechos Emisión', validators=[Optional()])
    tasas = StringField('Tasas', validators=[Optional()])
    nuevo = StringField('Nuevo', validators=[Optional()])
    pri_ma = StringField('Prima', validators=[Optional()])
    mar_ca = StringField('Marca', validators=[Optional()])
    tip_o = StringField('Tipo', validators=[Optional()])
    zon_a = StringField('Zona', validators=[Optional()])
    pro_duc = StringField('Productor', validators=[Optional()])
    age_nte = StringField('Agente', validators=[Optional()])
    acr_pre = StringField('Acreedor Prendario', validators=[Optional()])
    dir_acr = StringField('Dirección Acreedor', validators=[Optional()])
    cta_cte = StringField('Cuenta Corriente', validators=[Optional()])
    cobranza = StringField('Cobranza', validators=[Optional()])
    sec_cion = StringField('Sección', validators=[Optional()])
    siniestr = StringField('Siniestralidad', validators=[Optional()])
    fec_emic = StringField('Fecha Emisión', validators=[Optional()])
    control_hash = StringField('Control Hash', validators=[Optional()])
    dbf_source = StringField('DBF Source', validators=[Optional()])

    submit = SubmitField('Guardar')
