# models.py

from extensions import db

class SCliente(db.Model):
    __tablename__ = 'scliente'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nro_cli = db.Column(db.Text, nullable=True)
    num_soc = db.Column(db.Text, nullable=True)
    act_ivo = db.Column(db.Text, nullable=True)
    ape_cli = db.Column(db.Text, nullable=True)
    nom_cli = db.Column(db.Text, nullable=True)
    nombrer = db.Column(db.Text, nullable=True)
    dom_cli = db.Column(db.Text, nullable=True)
    loc_cli = db.Column(db.Text, nullable=True)
    postal = db.Column(db.Text, nullable=True)
    pro_cli = db.Column(db.Text, nullable=True)
    con_doc = db.Column(db.Text, nullable=True)
    doc_cli = db.Column(db.Text, nullable=True)
    nac_nal = db.Column(db.Text, nullable=True)
    tip_cui = db.Column(db.Text, nullable=True)
    cuit = db.Column(db.String(20), nullable=True)
    con_iva = db.Column(db.Text, nullable=True)
    nac_cli = db.Column(db.Text, nullable=True)
    est_civ = db.Column(db.Text, nullable=True)
    ocu_cli = db.Column(db.Text, nullable=True)
    act_cli = db.Column(db.Text, nullable=True)
    tel_fax = db.Column(db.Text, nullable=True)
    cia_ase = db.Column(db.Text, nullable=True)
    cip_cli = db.Column(db.Text, nullable=True)
    cip_cl2 = db.Column(db.Text, nullable=True)
    cip_cl3 = db.Column(db.Text, nullable=True)
    cip_end = db.Column(db.Text, nullable=True)
    cip_res = db.Column(db.Text, nullable=True)
    pol_iza = db.Column(db.Text, nullable=True)
    pol_iz2 = db.Column(db.Text, nullable=True)
    des_de = db.Column(db.Text, nullable=True)
    has_ta = db.Column(db.Text, nullable=True)
    cob_ert = db.Column(db.Text, nullable=True)
    for_pag = db.Column(db.Text, nullable=True)
    pat_ent = db.Column(db.Text, nullable=True)
    cha_sis = db.Column(db.Text, nullable=True)
    ano_mod = db.Column(db.Text, nullable=True)
    mot_or = db.Column(db.Text, nullable=True)
    val_or = db.Column(db.Text, nullable=True)
    uso_vei = db.Column(db.Text, nullable=True)
    res_civ = db.Column(db.Text, nullable=True)
    ant_cip = db.Column(db.Text, nullable=True)
    nro_rec = db.Column(db.Text, nullable=True)
    can_cuo = db.Column(db.Text, nullable=True)
    imp_cuo = db.Column(db.Text, nullable=True)
    tot_pol = db.Column(db.Text, nullable=True)
    pre_mio = db.Column(db.Text, nullable=True)
    recargos = db.Column(db.Text, nullable=True)
    deremi = db.Column(db.Text, nullable=True)
    tasas = db.Column(db.Text, nullable=True)
    nuevo = db.Column(db.Text, nullable=True)
    pri_ma = db.Column(db.Text, nullable=True)
    mar_ca = db.Column(db.Text, nullable=True)
    tip_o = db.Column(db.Text, nullable=True)
    zon_a = db.Column(db.Text, nullable=True)
    pro_duc = db.Column(db.Text, nullable=True)
    age_nte = db.Column(db.Text, nullable=True)
    acr_pre = db.Column(db.Text, nullable=True)
    dir_acr = db.Column(db.Text, nullable=True)
    cta_cte = db.Column(db.Text, nullable=True)
    cobranza = db.Column(db.Text, nullable=True)
    sec_cion = db.Column(db.Text, nullable=True)
    siniestr = db.Column(db.Text, nullable=True)
    fec_emic = db.Column(db.Text, nullable=True)
    control_hash = db.Column(db.String(32), unique=True, nullable=False)
    sync_date = db.Column(db.DateTime, server_default=db.func.current_timestamp())
    dbf_source = db.Column(db.String(255), nullable=True)

    def __repr__(self):
        return f"<SCliente id={self.id} ape_cli='{self.ape_cli}' nom_cli='{self.nom_cli}'>"
