"""Agrega la tabla user_data y la relacion con user

Revision ID: 10e9eff85f09
Revises: 5fcc915817d1
Create Date: 2025-07-31 15:21:27.789494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e9eff85f09'
down_revision = '5fcc915817d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id_userdata', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('cuil_dni', sa.String(length=20), nullable=False),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('nivel_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_userdata'),
    sa.UniqueConstraint('cuil_dni'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
