"""Agrega la tabla user_data y la relacion con user sin id

Revision ID: 118c238a2e78
Revises: 10e9eff85f09
Create Date: 2025-07-31 15:24:55.328893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '118c238a2e78'
down_revision = '10e9eff85f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('id_userdata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_userdata', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
