"""Initial migration

Revision ID: 1bb2d3ecc5d8
Revises: 
Create Date: 2025-08-01 01:45:22.971729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bb2d3ecc5d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibos', schema=None) as batch_op:
        batch_op.alter_column('pronro',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibos', schema=None) as batch_op:
        batch_op.alter_column('pronro',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
