"""Add is_verified field to User

Revision ID: c6840a7d4f9c
Revises: 34a9f833d161
Create Date: 2025-07-28 14:23:43.750922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6840a7d4f9c'
down_revision = '34a9f833d161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('categoria_producto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_producto', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
