"""Crear tabla recibos_new con tipos optimizados

Revision ID: d82cde035fc2
Revises: d1cb663d4a78
Create Date: 2025-08-02 04:20:20.701690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82cde035fc2'
down_revision = 'd1cb663d4a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recibos_new',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pronro', sa.String(length=20), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('num_cli', sa.String(length=20), nullable=True),
    sa.Column('planilla', sa.String(length=50), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('seccion', sa.String(length=50), nullable=True),
    sa.Column('poliza', sa.String(length=50), nullable=True),
    sa.Column('endoso', sa.String(length=50), nullable=True),
    sa.Column('operacion', sa.String(length=50), nullable=True),
    sa.Column('fec_ope', sa.DateTime(), nullable=True),
    sa.Column('fereal', sa.DateTime(), nullable=True),
    sa.Column('vencuot', sa.DateTime(), nullable=True),
    sa.Column('vdes', sa.DateTime(), nullable=True),
    sa.Column('vhas', sa.DateTime(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('prima', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rec', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deradm', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('impytas', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('premio', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('prerea', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nrorec', sa.String(length=50), nullable=True),
    sa.Column('nrocut', sa.String(length=50), nullable=True),
    sa.Column('codpro', sa.String(length=50), nullable=True),
    sa.Column('pend', sa.String(length=10), nullable=True),
    sa.Column('control_hash', sa.String(length=32), nullable=False),
    sa.Column('sync_date', sa.DateTime(), nullable=True),
    sa.Column('dbf_source', sa.String(length=255), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_id'], ['recibos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recibos_new')
    # ### end Alembic commands ###
